DienMayQuyetTien/Models/InstallmentBillDetail.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DienMayQuyetTien.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class InstallmentBillDetail
    {
        public int ID { get; set; }
        public int BillID { get; set; }
        public int ProductID { get; set; }

        [Required(ErrorMessage = "Vui lòng nhập Số lượng")]
        public int Quantity { get; set; }

        [Required(ErrorMessage = "Vui lòng nhập Số lượng")]
        public int InstallmentPrice { get; set; }
    
        public virtual InstallmentBill InstallmentBill { get; set; }
        public virtual Product Product { get; set; }
    }
}

DienMayQuyetTien/Areas/Employee/Controllers/InstallmentBillDetailsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DienMayQuyetTien.Models;

namespace DienMayQuyetTien.Areas.Employee.Controllers
{
    public class InstallmentBillDetailsController : Controller
    {
        private DmQT07Entities1 db = new DmQT07Entities1();

        // GET: Employee/InstallmentBillDetails
        public PartialViewResult Index()
        {
            if (Session["InstallmentBillDetail"] == null)
                Session["InstallmentBillDetail"] = new List<InstallmentBillDetail>();
            return PartialView(Session["InstallmentBillDetail"]);
        }

        // GET: Employee/InstallmentBillDetails/Details/5
        //public ActionResult Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    InstallmentBillDetail installmentBillDetail = db.InstallmentBillDetails.Find(id);
        //    if (installmentBillDetail == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(installmentBillDetail);
        //}
        public int InstallmentPrice(int ProductID)
        {
            return db.Products.Find(ProductID).InstallmentPrice;
        }

        // GET: Employee/InstallmentBillDetails/Create
        public PartialViewResult Create()
        {
            ViewBag.ProductID = new SelectList(db.Products, "ID", "ProductName");
            var model = new InstallmentBillDetail();
            model.BillID = 0;
            model.Quantity = 1;
            return PartialView(model);
        }

        // POST: Employee/InstallmentBillDetails/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create2(InstallmentBillDetail model)
        {
            if (ModelState.IsValid)
            {
                model.ID = Environment.TickCount;
                model.Product = db.Products.Find(model.ProductID);
                var installmentBillDetail = Session["InstallmentBillDetail"] as List<InstallmentBillDetail>;
                if (installmentBillDetail == null)
                {
                    installmentBillDetail = new List<InstallmentBillDetail>();

                }
                installmentBillDetail.Add(model);
                Session["InstallmentBillDetail"] = installmentBillDetail;
                return RedirectToAction("Create", "ManageInstallmentBill");
            }

            //ViewBag.BillID = new SelectList(db.InstallmentBills, "ID", "BillCode", installmentBillDetail.BillID);
            ViewBag.ProductID = new SelectList(db.Products, "ID", "ProductName", model.ProductID);
            return View("Create", model);
        }

        // GET: Employee/InstallmentBillDetails/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            InstallmentBillDetail installmentBillDetail = db.InstallmentBillDetails.Find(id);
            if (installmentBillDetail == null)
            {
                return HttpNotFound();
            }
            ViewBag.BillID = new SelectList(db.InstallmentBills, "ID", "BillCode", installmentBillDetail.BillID);
            ViewBag.ProductID = new SelectList(db.Products, "ID", "ProductCode", installmentBillDetail.ProductID);
            return View(installmentBillDetail);
        }

        // POST: Employee/InstallmentBillDetails/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,BillID,ProductID,Quantity,InstallmentPrice")] InstallmentBillDetail installmentBillDetail)
        {
            if (ModelState.IsValid)
            {
                db.Entry(installmentBillDetail).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.BillID = new SelectList(db.InstallmentBills, "ID", "BillCode", installmentBillDetail.BillID);
            ViewBag.ProductID = new SelectList(db.Products, "ID", "ProductCode", installmentBillDetail.ProductID);
            return View(installmentBillDetail);
        }

        // GET: Employee/InstallmentBillDetails/Delete/5
        public ActionResult Delete(int? id)
        {
            var CTHoaDonTG = Session["InstallmentBillDetail"] as List<InstallmentBillDetail>;
            CTHoaDonTG = CTHoaDonTG.Except(CTHoaDonTG.Where(c => c.ID == id)).ToList();
            Session["InstallmentBillDetail"] = CTHoaDonTG;
            return RedirectToAction("Create", "ManageInstallmentBill");
        }

        // POST: Employee/InstallmentBillDetails/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            InstallmentBillDetail installmentBillDetail = db.InstallmentBillDetails.Find(id);
            db.InstallmentBillDetails.Remove(installmentBillDetail);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DienMayQuyetTien/Areas/Employee/Views/InstallmentBillDetails/Create.cshtml
@model DienMayQuyetTien.Models.InstallmentBillDetail

@{
    ViewBag.Title = "Create";
}


@using (Html.BeginForm("Create2", "InstallmentBillDetails"))
{
    @Html.AntiForgeryToken()
<div class="form-horizontal">
    <h4>Thêm sản phẩm</h4>
    <hr />
    @Html.ValidationSummary(true)
    @Html.HiddenFor(model => model.BillID)
    <div class="row">
        <div class="form-group col-md-6">
            @Html.LabelFor(model => model.ProductID, "Sản phẩm", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.ProductID, (SelectList)ViewData["ProductID"], String.Empty)
                @Html.ValidationMessageFor(model => model.ProductID)
            </div>
        </div>

        <div class="form-group col-md-6">
            @Html.LabelFor(model => model.InstallmentBill, "Đơn giá bán", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.InstallmentPrice, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.InstallmentPrice)
            </div>
        </div>
    </div>

    <div class="row">
        <div class="form-group col-md-6">
            @Html.LabelFor(model => model.Quantity, "Số lượng", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quantity)
                @Html.ValidationMessageFor(model => model.Quantity)
            </div>
        </div>

        <div class="form-group col-md-6">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Thêm sản phẩm" class="btn btn-success" />
            </div>
        </div>
    </div>
</div>
}

DienMayQuyetTien/Areas/Employee/Views/InstallmentBillDetails/Delete.cshtml
@model DienMayQuyetTien.Models.InstallmentBillDetail

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Employee/Views/Shared/_EmpLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>InstallmentBillDetail</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.InstallmentPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.InstallmentPrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.InstallmentBill.BillCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.InstallmentBill.BillCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Product.ProductCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Product.ProductCode)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

DienMayQuyetTien/Areas/Employee/Views/InstallmentBillDetails/Details.cshtml
@model DienMayQuyetTien.Models.InstallmentBillDetail

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Employee/Views/Shared/_EmpLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>InstallmentBillDetail</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.InstallmentPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.InstallmentPrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.InstallmentBill.BillCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.InstallmentBill.BillCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Product.ProductCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Product.ProductCode)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

DienMayQuyetTien/Areas/Employee/Views/InstallmentBillDetails/Edit.cshtml
@model DienMayQuyetTien.Models.InstallmentBillDetail

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Employee/Views/Shared/_EmpLayout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>InstallmentBillDetail</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.BillID, "BillID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("BillID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.BillID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductID, "ProductID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ProductID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ProductID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.InstallmentPrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.InstallmentPrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.InstallmentPrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DienMayQuyetTien/Areas/Employee/Views/InstallmentBillDetails/Index.cshtml
@model IEnumerable<DienMayQuyetTien.Models.InstallmentBillDetail>

@{
    ViewBag.Title = "Index";
}

<h4>Thông tin các sản phẩm</h4>

<table class="table">
    <tr>
        <th>
            Mã sản phẩm
        </th>
        <th>
            Tên sản phẩm
        </th>
        <th>
            Số lượng
        </th>
        <th>
            Giá bán
        </th>
        <th>
            Tổng
        </th>

        <th></th>
    </tr>

    @foreach (var item in Model)
    {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Product.ProductCode)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Product.ProductName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Quantity)
        </td>
        <td>
            @String.Format("{0:0,0}", item.InstallmentPrice)
        </td>
        <td>
            @String.Format("{0:0,0}", item.InstallmentPrice * item.Quantity)
        </td>

        <td>
            <button class="btn btn-danger" onclick="location.href='@Url.Action("Delete", "InstallmentBillDetails", new { id = item.ID })'"><i class="fa fa-trash"></i></button>
        </td>
    </tr>
    }

</table>
<div>
    <div class="form-group">
        <label class="control-label col-md-2">Tổng tiền</label>
        <div class="col-md-10">
            @{var total = Model.Sum(m => m.InstallmentPrice * m.Quantity);
                Session["Total"] = total;
            }
            <input class="disabled" value="@Model.Sum(m => m.InstallmentPrice * m.Quantity)" disabled /> VNĐ
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-2" required>Tiền trả trước</label>
        <div class="col-md-10">
            <input type="number" value="" id="taken" /> VNĐ
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-2">Tiền còn lại</label>
        <div class="col-md-10">
            <input type="text" id="remain" value="" disabled required/> VNĐ
        </div>
    </div>
</div>