DienMayQuyetTien/Areas/Admin/Controllers/ManageProductTypeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DienMayQuyetTien.Models;

namespace DienMayQuyetTien.Areas.Admin.Controllers
{
    public class ManageProductTypeController : Controller
    {
        private DmQT07Entities1 db = new DmQT07Entities1();

        // GET: Admin/ManageProductType
        public ActionResult Index()
        {
            if (Session["username"] != null && Session["authority"].ToString() == "Quản lí")
            {
                return View(db.ProductTypes.ToList());
            }
            else
            {
                return RedirectToAction("Login", "Login", new { area = "" });
            }
            
        }

        // GET: Admin/ManageProductType/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductType productType = db.ProductTypes.Find(id);
            if (productType == null)
            {
                return HttpNotFound();
            }
            if (Session["username"] != null && Session["authority"].ToString() == "Quản lí")
            {
                return View(productType);
            }
            else
            {
                return RedirectToAction("Login", "Login", new { area = "" });
            }
            
        }

        // GET: Admin/ManageProductType/Create
        public ActionResult Create()
        {
            if (Session["username"] != null && Session["authority"].ToString() == "Quản lí")
            {
                return View();
            }
            else
            {
                return RedirectToAction("Login", "Login", new { area = "" });
            }
        }

        // POST: Admin/ManageProductType/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,ProductTypeCode,ProductTypeName")] ProductType productType)
        {
            if (ModelState.IsValid)
            {
                db.ProductTypes.Add(productType);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            if (Session["username"] != null && Session["authority"].ToString() == "Quản lí")
            {
                return View(productType);
            }
            else
            {
                return RedirectToAction("Login", "Login", new { area = "" });
            }
        }

        // GET: Admin/ManageProductType/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductType productType = db.ProductTypes.Find(id);
            if (productType == null)
            {
                return HttpNotFound();
            }
            if (Session["username"] != null && Session["authority"].ToString() == "Quản lí")
            {
                return View(productType);
            }
            else
            {
                return RedirectToAction("Login", "Login", new { area = "" });
            }
        }

        // POST: Admin/ManageProductType/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,ProductTypeCode,ProductTypeName")] ProductType productType)
        {
            if (ModelState.IsValid)
            {
                db.Entry(productType).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            if (Session["username"] != null && Session["authority"].ToString() == "Quản lí")
            {
                return View(productType);
            }
            else
            {
                return RedirectToAction("Login", "Login", new { area = "" });
            }
        }

        // GET: Admin/ManageProductType/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductType productType = db.ProductTypes.Find(id);
            if (productType == null)
            {
                return HttpNotFound();
            }
            if (Session["username"] != null && Session["authority"].ToString() == "Quản lí")
            {
                return View(productType);
            }
            else
            {
                return RedirectToAction("Login", "Login", new { area = "" });
            }
        }

        // POST: Admin/ManageProductType/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ProductType productType = db.ProductTypes.Find(id);
            db.ProductTypes.Remove(productType);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DienMayQuyetTien/Areas/Employee/Controllers/ManageProductTypeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DienMayQuyetTien.Models;

namespace DienMayQuyetTien.Areas.Employee.Controllers
{
    public class ManageProductTypeController : Controller
    {
        private DmQT07Entities1 db = new DmQT07Entities1();

        // GET: Admin/ManageProductType
        public ActionResult Index()
        {
            if (Session["username"] != null && Session["authority"].ToString() == "Nhân viên bán hàng")
            {
                var product = db.Products.OrderByDescending(x => x.ID).ToList();
                return View(product);
            }
            else
            {
                return RedirectToAction("Login", "Login", new { area = "" });
            }
            
        }

        // GET: Admin/ManageProductType/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductType productType = db.ProductTypes.Find(id);
            if (productType == null)
            {
                return HttpNotFound();
            }
            if (Session["username"] != null && Session["authority"].ToString() == "Nhân viên bán hàng")
            {
                return View(productType);
            }
            else
            {
                return RedirectToAction("Login", "Login", new { area = "" });
            }
            
        }

        // GET: Admin/ManageProductType/Create
        public ActionResult Create()
        {
            if (Session["username"] != null && Session["authority"].ToString() == "Nhân viên bán hàng")
            {
                return View();
            }
            else
            {
                return RedirectToAction("Login", "Login", new { area = "" });
            }
        }

        // POST: Admin/ManageProductType/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,ProductTypeCode,ProductTypeName")] ProductType productType)
        {
            if (ModelState.IsValid)
            {
                db.ProductTypes.Add(productType);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            if (Session["username"] != null && Session["authority"].ToString() == "Nhân viên bán hàng")
            {
                return View(productType);
            }
            else
            {
                return RedirectToAction("Login", "Login", new { area = "" });
            }
        }

        // GET: Admin/ManageProductType/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductType productType = db.ProductTypes.Find(id);
            if (productType == null)
            {
                return HttpNotFound();
            }
            if (Session["username"] != null && Session["authority"].ToString() == "Nhân viên bán hàng")
            {
                return View(productType);
            }
            else
            {
                return RedirectToAction("Login", "Login", new { area = "" });
            }
        }

        // POST: Admin/ManageProductType/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,ProductTypeCode,ProductTypeName")] ProductType productType)
        {
            if (ModelState.IsValid)
            {
                db.Entry(productType).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            if (Session["username"] != null && Session["authority"].ToString() == "Nhân viên bán hàng")
            {
                return View(productType);
            }
            else
            {
                return RedirectToAction("Login", "Login", new { area = "" });
            }
        }

        // GET: Admin/ManageProductType/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductType productType = db.ProductTypes.Find(id);
            if (productType == null)
            {
                return HttpNotFound();
            }
            if (Session["username"] != null && Session["authority"].ToString() == "Nhân viên bán hàng")
            {
                return View(productType);
            }
            else
            {
                return RedirectToAction("Login", "Login", new { area = "" });
            }
        }

        // POST: Admin/ManageProductType/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ProductType productType = db.ProductTypes.Find(id);
            db.ProductTypes.Remove(productType);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DienMayQuyetTien/Areas/Employee/Views/ManageProductType/Create.cshtml
@model DienMayQuyetTien.Models.ProductType

@{
    ViewBag.Title = "Thêm loại sản phẩm";
    Layout = "~/Areas/Employee/Views/Shared/_EmpLayout.cshtml";
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-control" align="center" style="  border: 1px solid;
            padding: 10px;
                box-shadow: 5px 5px #888888;border-radius: 15px; width:400px;">
    <h2>Thêm loại sản phẩm</h2>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.ProductTypeCode, "Mã loại sản phẩm", htmlAttributes: new { @class = "control-label col-md-6" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ProductTypeCode, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ProductTypeCode, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ProductTypeName, "Tên loại sản phẩm", htmlAttributes: new { @class = "control-label col-md-6" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ProductTypeName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ProductTypeName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <button type="submit" class="btn btn-success">Thêm</button>
            @Html.ActionLink("Hủy", "Index", "ManageProductType", null, new { @class = "btn btn-danger" })
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Trở về danh sách", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DienMayQuyetTien/Areas/Employee/Views/ManageProductType/Delete.cshtml
@model DienMayQuyetTien.Models.ProductType

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Employee/Views/Shared/_EmpLayout.cshtml";
}
<h3>Bạn có chắc chắn muốn xóa loại sản phẩm này?</h3>
<div>
    <hr />
    <dl class="dl-horizontal" align="center" style="  border: 1px solid;
            padding: 10px;
                box-shadow: 5px 5px #888888;border-radius: 15px; width:500px;">
        <h2>Xóa loại sản phẩm</h2>
        <dt>
            Mã loại sản phẩm
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductTypeCode)
        </dd>

        <dt>
            Tên loại sản phẩm
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductTypeName)
        </dd>
        <dd>
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-actions no-color">
                    <button type="submit" class="btn btn-danger">Xóa</button> |
                    @Html.ActionLink("Hủy", "Index")
                </div>
            }
        </dd>

    </dl>

</div>

DienMayQuyetTien/Areas/Employee/Views/ManageProductType/Details.cshtml
@model DienMayQuyetTien.Models.ProductType

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Employee/Views/Shared/_EmpLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>ProductType</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ProductTypeCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductTypeCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProductTypeName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductTypeName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

DienMayQuyetTien/Areas/Employee/Views/ManageProductType/Edit.cshtml
@model DienMayQuyetTien.Models.ProductType

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Employee/Views/Shared/_EmpLayout.cshtml";
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-control" align="center" style="  border: 1px solid;
            padding: 10px;
                box-shadow: 5px 5px #888888;border-radius: 15px; width:400px;">
    <h2>Chỉnh sửa loại sản phẩm</h2>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.ID)

    <div class="form-group">
        @Html.LabelFor(model => model.ProductTypeCode, "Mã loại sản phẩm", htmlAttributes: new { @class = "control-label col-md-6" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ProductTypeCode, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ProductTypeCode, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ProductTypeName, "Tên loại sản phẩm", htmlAttributes: new { @class = "control-label col-md-6" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ProductTypeName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ProductTypeName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <button type="submit" class="btn btn-primary">Lưu</button>
            @Html.ActionLink("Hủy", "Index", "ManageProductType", null, new { @class = "btn btn-danger" })
        </div>
    </div>
</div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DienMayQuyetTien/Areas/Employee/Views/ManageProductType/Index.cshtml
@model IEnumerable<DienMayQuyetTien.Models.ProductType>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Employee/Views/Shared/_EmpLayout.cshtml";
}

<h2>Quản lí loại sản phẩm</h2>

<p>
    <button class="btn btn-success" onclick="location.href='@Url.Action("Create", "ManageProductType")'"><i class="fa fa-plus"></i> Thêm loại sản phẩm</button>
</p>
<div class="card mb-3">
    <div class="card-header">
        <i class="fa fa-table"></i> Bảng loại sản phẩm
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead align="center">
                    <tr>
                        <th>Mã loại sản phẩm</th>
                        <th>Tên loại sản phẩm</th>
                        <th>Tùy chọn</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.ProductTypeCode)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.ProductTypeName)
                            </td>
                            <td>
                                <button class="btn btn-info" onclick="location.href='@Url.Action("Edit", "ManageProductType", new { id = item.ID })'"><i class="fa fa-pencil"></i></button>
                                <button class="btn btn-danger" onclick="location.href='@Url.Action("Delete", "ManageProductType", new { id = item.ID })'"><i class="fa fa-trash"></i></button>
                            </td>
                        </tr>
                    }

                </tbody>
            </table>
        </div>
    </div>
    <div class="card-footer small text-muted"></div>

</div>