DienMayQuyetTien/Areas/Employee/Controllers/ManageInstallmentBillController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Transactions;
using System.Web;
using System.Web.Mvc;
using DienMayQuyetTien.Areas.Employee.Models;
using DienMayQuyetTien.Models;

namespace DienMayQuyetTien.Areas.Employee.Controllers
{
    public class ManageInstallmentBillController : Controller
    {
        private DmQT07Entities1 db = new DmQT07Entities1();      

        // GET: Employee/ManageInstallmentBill
        public ActionResult Index()
        {
            if (Session["username"] != null && Session["authority"].ToString() == "Nhân viên bán hàng")
            {
                return View(db.InstallmentBills.ToList());
            }
            else
            {
                return RedirectToAction("Login", "Login", new { area = "" });
            }
        }
        public int setSessionTaken(int taken)
        {
            Session["Taken"] = taken;
            return (int)Session["Taken"];
        }

        // GET: Employee/ManageInstallmentBill/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            InstallmentBill installmentBill = db.InstallmentBills.Find(id);
            if (installmentBill == null)
            {
                return HttpNotFound();
            }
            if (Session["username"] != null && Session["authority"].ToString() == "Nhân viên bán hàng")
            {

                return View(installmentBill);
            }
            else
            {
                return RedirectToAction("Login", "Login", new { area = "" });
            }
        }

        // GET: Employee/ManageInstallmentBill/Create
        public ActionResult Create()
        {
            if (Session["username"] != null && Session["authority"].ToString() == "Nhân viên bán hàng")
            {
               
                ViewBag.CustomerID = new SelectList((from s in db.Customers select new { ID = s.ID, Info = s.CustomerCode + " - " + s.CustomerName }), "ID", "Info", null);
                return View(Session["InstallmentBill"]);
            }
            else
            {
                return RedirectToAction("Login", "Login", new { area = "" });
            }
        }

        // POST: Employee/ManageInstallmentBill/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(InstallmentBill model)
        {
            //CheckInstallmentBill(model);
            if (ModelState.IsValid)
            {
                
                Session["InstallmentBill"] = model;
            }

            if (Session["username"] != null && Session["authority"].ToString() == "Nhân viên bán hàng")
            {
                ViewBag.CustomerID = new SelectList((from s in db.Customers select new { ID = s.ID, Info = s.CustomerCode + " - " + s.CustomerName }), "ID", "Info", null);
                return View(model);
            }
            else
            {
                return RedirectToAction("Login", "Login", new { area = "" });
            }
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create2()
        {
            using (var scope = new TransactionScope())
                try
                {
                    var installmentBill = Session["InstallmentBill"] as InstallmentBill;
                    var installmentBillDetail = Session["InstallmentBillDetail"] as List<InstallmentBillDetail>;
                    installmentBill.Date = DateTime.Now;
                    installmentBill.GrandTotal = (int)Session["Total"];
                    installmentBill.Taken = (int)Session["Taken"];
                    installmentBill.Remain = ((int)Session["Total"] - (int)Session["Taken"]);
                    db.InstallmentBills.Add(installmentBill);
                    db.SaveChanges();

                    foreach (var detail in installmentBillDetail)
                    {
                        detail.BillID = installmentBill.ID;
                        detail.Product = null;
                        db.InstallmentBillDetails.Add(detail);
                    }
                    db.SaveChanges();
                    scope.Complete();

                    Session["InstallmentBill"] = null;
                    Session["InstallmentBillDetail"] = null;
                    Session["Total"] = null;
                    Session["Taken"] = null;
                    return RedirectToAction("Index");
                }
                catch (Exception e)
                {
                    ModelState.AddModelError("", e.Message);
                }
            
            if (Session["username"] != null && Session["authority"].ToString() == "Nhân viên bán hàng")
            {
                return View("Create");
            }
            else
            {
                return RedirectToAction("Login", "Login", new { area = "" });
            }

        }
        // GET: Employee/ManageInstallmentBill/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            InstallmentBill installmentBill = db.InstallmentBills.Find(id);
            if (installmentBill == null)
            {
                return HttpNotFound();
            }
            ViewBag.CustomerID = new SelectList(db.Customers, "ID", "CustomerCode", installmentBill.CustomerID);
            if (Session["username"] != null && Session["authority"].ToString() == "Nhân viên bán hàng")
            {
                return View(installmentBill);
            }
            else
            {
                return RedirectToAction("Login", "Login", new { area = "" });
            }
            
        }

        // POST: Employee/ManageInstallmentBill/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,BillCode,CustomerID,Date,Shipper,Note,Method,Period,GrandTotal,Taken,Remain")] InstallmentBill installmentBill)
        {
            if (ModelState.IsValid)
            {
                db.Entry(installmentBill).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CustomerID = new SelectList(db.Customers, "ID", "CustomerCode", installmentBill.CustomerID);
            if (Session["username"] != null && Session["authority"].ToString() == "Nhân viên bán hàng")
            {
                return View(installmentBill);
            }
            else
            {
                return RedirectToAction("Login", "Login", new { area = "" });
            }
        }
        private void CheckInstallmentBill(InstallmentBill model)
        {

            if (model.Method.Length <= 0)
                ModelState.AddModelError("Method", "Độ dài lớn hơn 0");
            if (model.Period <= 0)
                ModelState.AddModelError("Period", "Thời hạn trả góp phải lớn hơn 0");
        }

        public ActionResult Print(int id)
        {
            var order = db.InstallmentBills.FirstOrDefault(o => o.ID == id);
            if (order != null)
            {
                InstallmentBillModel rp = new InstallmentBillModel();
                rp.BillCode = order.BillCode;
                rp.CustomerID = order.CustomerID;
                rp.Date = order.Date;
                rp.Shipper = order.Shipper;
                rp.Note = order.Note;
                rp.Method = order.Method;
                rp.Period = order.Period;
                rp.GrandTotal = order.GrandTotal;
                rp.Taken = order.Taken;
                rp.Remain = order.Remain;
                rp.Customer = order.Customer;
                rp.InstallmentBillDetail = order.InstallmentBillDetails.ToList();
                if (Session["username"] != null && Session["authority"].ToString() == "Nhân viên bán hàng")
                {
                    return View(rp);
                }
                else
                {
                    return RedirectToAction("Login", "Login", new { area = "" });
                }
                
            }
            else
            {

                if (Session["username"] != null && Session["authority"].ToString() == "Nhân viên bán hàng")
                {
                    return View();
                }
                else
                {
                    return RedirectToAction("Login", "Login", new { area = "" });
                }
            }
        }
    }
}

DienMayQuyetTien/Areas/Employee/Views/ManageInstallmentBill/Create.cshtml
@model DienMayQuyetTien.Models.InstallmentBill

@{
    ViewBag.Title = "Thêm hóa đơn trả góp";
    Layout = "~/Areas/Employee/Views/Shared/_EmpLayout.cshtml";

}

<h2>THÊM HÓA ĐƠN TRẢ GÓP</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">

        <h4>Thông tin hóa đơn</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="row">

            <div class="col-md-10" style="margin-bottom:30px; margin-left:15px;">
                Ngày lập hóa đơn: <em>@DateTime.Now</em>

            </div>
            <div class="form-group col-md-6">
                @Html.LabelFor(model => model.CustomerID, "Chọn khách hàng", htmlAttributes: new { @class = "control-label col-md-6" })
                <div class="col-md-10">

                    @Html.DropDownList("CustomerID", (IEnumerable<SelectListItem>)ViewData["CustomerID"], htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.CustomerID)
                </div>
            </div>
        <div class="form-group col-md-6">
            @Html.LabelFor(model => model.Shipper, "Người giao hàng", new { @class = "control-label col-md-6" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Shipper)
                @Html.ValidationMessageFor(model => model.Shipper)
            </div>
        </div>
    </div>

    <div class="row">
        <div class="form-group col-md-6">
            @Html.LabelFor(model => model.Method, "Hình thức trả góp", new { @class = "control-label col-md-6" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Method)
                @Html.ValidationMessageFor(model => model.Method)
            </div>
        </div>
        <div class="form-group col-md-6">
            @Html.LabelFor(model => model.Period, "Thời hạn trả góp", new { @class = "control-label col-md-6" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Period, new { type = "number" })
                @Html.ValidationMessageFor(model => model.Period)
            </div>
        </div>

        <div class="form-group col-md-6">
            @Html.LabelFor(model => model.Note, "Ghi chú", new { @class = "control-label col-md-6" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Note)
                @Html.ValidationMessageFor(model => model.Note)
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type = "submit" value="Lưu hóa đơn" class="btn btn-primary" />
        </div>
    </div>
</div>
}

@if(Session["InstallmentBill"] != null)
{

    @Html.Action("Create", "InstallmentBillDetails")
    @Html.Action("Index", "InstallmentBillDetails")

    <br/><br/>
    using (Html.BeginForm("Create2", "ManageInstallmentBill"))
    {
        @Html.AntiForgeryToken()
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type = "submit" value="Lập hóa đơn" class="btn btn-primary" />

            </div>
        </div>
    }

}
<div>
@Html.ActionLink("Trở về danh sách", "Index")

</div>

@section Scripts
{

    <script>
    function getInstallmentPrice(ProductID) {
        var url = '@Url.Action("InstallmentPrice", "InstallmentBillDetails")';
        url = url + '?ProductID=' + ProductID
        $.get(url, function (data) {
            $('#InstallmentPrice').val(data);
        });
    }
            $(document).ready(function () {
                var ProductID = $("#ProductID").children("option:selected").val();
                getInstallmentPrice(ProductID);
            });
            $('#ProductID').change(function () {
                getInstallmentPrice($(this).val());
            });

            $('#taken').change(function () {
                var taken = $('#taken').val();

                var url = '@Url.Action("setSessionTaken", "ManageInstallmentBill")';
                url = url + '?taken=' + taken
                $.get(url, function (data) {
                    $('#remain').val(@Session["Total"] - data);
                });
            })
    $('#ProductID').change(function () {
    var url = '@Url.Action("InstallmentPrice", "InstallmentBillDetails")';
    url = url + '?ProductID=' + $(this).val();
    $.get(url, function (data) {
    $('#InstallmentPrice').val(data);
    });
    });
    </script>
                    }

DienMayQuyetTien/Areas/Employee/Views/ManageInstallmentBill/Delete.cshtml
@model DienMayQuyetTien.Models.InstallmentBill

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Employee/Views/Shared/_EmpLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>InstallmentBill</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.BillCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BillCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Shipper)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Shipper)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Note)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Note)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Method)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Method)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Period)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Period)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GrandTotal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GrandTotal)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Taken)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Taken)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Remain)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Remain)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Customer.CustomerCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Customer.CustomerCode)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

DienMayQuyetTien/Areas/Employee/Views/ManageInstallmentBill/Details.cshtml
@model DienMayQuyetTien.Models.InstallmentBill

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Employee/Views/Shared/_EmpLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>InstallmentBill</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.BillCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BillCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Shipper)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Shipper)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Note)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Note)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Method)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Method)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Period)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Period)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GrandTotal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GrandTotal)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Taken)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Taken)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Remain)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Remain)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Customer.CustomerCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Customer.CustomerCode)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

DienMayQuyetTien/Areas/Employee/Views/ManageInstallmentBill/Edit.cshtml
@model DienMayQuyetTien.Models.InstallmentBill

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Employee/Views/Shared/_EmpLayout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>InstallmentBill</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.BillCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BillCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BillCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CustomerID, "CustomerID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CustomerID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CustomerID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Shipper, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Shipper, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Shipper, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Note, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Note, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Note, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Method, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Method, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Method, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Period, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Period, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Period, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GrandTotal, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GrandTotal, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GrandTotal, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Taken, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Taken, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Taken, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Remain, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Remain, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Remain, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DienMayQuyetTien/Areas/Employee/Views/ManageInstallmentBill/Index.cshtml
@model IEnumerable<DienMayQuyetTien.Models.InstallmentBill>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Employee/Views/Shared/_EmpLayout.cshtml";
}

<h2>Quản lí hóa đơn trả góp</h2>

<p>
    <button class="btn btn-success" onclick="location.href='@Url.Action("Create", "ManageInstallmentBill")'"><i class="fa fa-plus"></i> Thêm hóa đơn</button>
</p>
<div class="card mb-3">
    <div class="card-header">
        <i class="fa fa-table"></i> Bảng hóa đơn trả góp
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead align="center">
                    <tr>
                        <th>
                            Mã hóa đơn
                        </th>
                        <th>
                            Ngày giờ
                        </th>
                        <th>
                            Người giao hàng
                        </th>
                        <th>
                            Ghi chú
                        </th>
                        <th>
                            Phương thức trả góp
                        </th>
                        <th>
                            Thời hạn trả góp
                        </th>
                        <th>
                            Tổng tiền(VNĐ)
                        </th>
                        <th>
                            Đã trả(VNĐ)
                        </th>
                        <th>
                            Còn lại(VNĐ)
                        </th>
                        <th>
                            Số CMND khách hàng
                        </th>
                        <th>Tùy chọn</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th>
                            Mã hóa đơn
                        </th>
                        <th>
                            Ngày giờ
                        </th>
                        <th>
                            Người giao hàng
                        </th>
                        <th>
                            Ghi chú
                        </th>
                        <th>
                            Phương thức trả góp
                        </th>
                        <th>
                            Thời hạn trả góp
                        </th>
                        <th>
                            Tổng tiền(VNĐ)
                        </th>
                        <th>
                            Đã trả(VNĐ)
                        </th>
                        <th>
                            Còn lại(VNĐ)
                        </th>
                        <th>
                            Số CMND khách hàng
                        </th>
                        <th>Tùy chọn</th>
                    </tr>
                </tfoot>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.BillCode)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Date)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Shipper)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Note)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Method)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Period)
                            </td>
                            <td>
                                @String.Format("{0:0,0}", item.GrandTotal)
                            </td>
                            <td>
                                @String.Format("{0:0,0}", item.Taken)
                            </td>
                            <td>
                                @String.Format("{0:0,0}", item.Remain)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Customer.CustomerCode)
                            </td>
                            <td>
                                <button class="btn btn-info" onclick="location.href='@Url.Action("Edit", "ManageInstallmentBill", new { id = item.ID })'"><i class="fa fa-pencil"></i></button>
                                <button class="btn btn-danger" onclick="location.href='@Url.Action("Print", "ManageInstallmentBill", new { id = item.ID })'"><i class="fa fa-print"></i></button>
                            </td>
                        </tr>
                    }

                </tbody>
            </table>
        </div>
    </div>
    <div class="card-footer small text-muted"></div>

</div>