DienMayQuyetTien/Areas/Employee/Controllers/ManageNewsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Transactions;
using System.Web;
using System.Web.Mvc;
using DienMayQuyetTien.Models;

namespace DienMayQuyetTien.Areas.Employee.Controllers
{
    public class ManageNewsController : Controller
    {
        private DmQT07Entities1 db = new DmQT07Entities1();

        // GET: Employee/ManageNews
        public ActionResult Index()
        {
            if (Session["username"] != null && Session["authority"].ToString() == "Nhân viên bán hàng")
            {
                return View(db.News.ToList());
            }
            else
            {
                return RedirectToAction("Login", "Login", new { area = "" });
            }

        }

        // GET: Employee/ManageNews/Details/5
        public ActionResult Details(string imageName)
        {
            var path = Server.MapPath("~/Images/" + imageName);
            return File(path, "images");
        }

        // GET: Employee/ManageNews/Create
        public ActionResult Create()
        {
            if (Session["username"] != null && Session["authority"].ToString() == "Nhân viên bán hàng")
            {
                return View(Session["News"]);
            }
            else
            {
                return RedirectToAction("Login", "Login", new { area = "" });
            }
        }

        // POST: Employee/ManageNews/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(News news)
        {
            if (news.ImageFile == null)
            {
                ModelState.AddModelError("ImageFile", "Chưa có hình sản phẩm!");
            }
            if (ModelState.IsValid)
            {
                using (var scope = new TransactionScope())
                {
                    db.News.Add(news);

                    if (news.ImageFile != null)
                    {
                        var imageName = System.IO.Path.GetFileName(news.ImageFile.FileName);
                        var path = Server.MapPath("~/Images");
                        path = System.IO.Path.Combine(path, imageName);
                        news.ImageFile.SaveAs(path);
                        news.Img = imageName;
                    }
                    db.SaveChanges();
                    scope.Complete();
                    return RedirectToAction("Index");

                }
            }

            if (Session["username"] != null && Session["authority"].ToString() == "Nhân viên bán hàng")
            {
                return View(news);
            }
            else
            {
                return RedirectToAction("Login", "Login", new { area = "" });
            }


        }

        // GET: Employee/ManageNews/Edit/5
        public ActionResult Edit(int? id)
        {

            News news = db.News.Find(id);
            if (news == null)
            {
                return HttpNotFound();
            }
            if (Session["username"] != null && Session["authority"].ToString() == "Nhân viên bán hàng")
            {
                return View(news);
            }
            else
            {
                return RedirectToAction("Login", "Login", new { area = "" });
            }

        }

        // POST: Employee/ManageNews/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(News news)
        {
            if (news.ImageFile == null)
            {
                News thisNew = db.News.Where(p => p.Id == news.Id).FirstOrDefault();
                news.Img = thisNew.Img;
            }
            if (ModelState.IsValid)
            {
                using (var scope = new TransactionScope())
                {
                    News thisNew = db.News.Where(p => p.Id == news.Id).FirstOrDefault();



                    if (news.ImageFile != null)
                    {
                        var imageName = System.IO.Path.GetFileName(news.ImageFile.FileName);
                        var path = Server.MapPath("~/Images");
                        path = System.IO.Path.Combine(path, imageName);
                        news.ImageFile.SaveAs(path);
                        news.Img = imageName;
                    }
                    db.Entry(thisNew).CurrentValues.SetValues(news);
                    db.SaveChanges();
                    scope.Complete();
                    return RedirectToAction("Index");

                }
            }
            if (Session["username"] != null && Session["authority"].ToString() == "Nhân viên bán hàng")
            {
                return View(news);
            }
            else
            {
                return RedirectToAction("Login", "Login", new { area = "" });
            }
        }

        // GET: Employee/ManageNews/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            News news = db.News.Find(id);
            if (news == null)
            {
                return HttpNotFound();
            }
            if (Session["username"] != null && Session["authority"].ToString() == "Nhân viên bán hàng")
            {
                return View(news);
            }
            else
            {
                return RedirectToAction("Login", "Login", new { area = "" });
            }

        }

        // POST: Employee/ManageNews/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            News news = db.News.Find(id);
            db.News.Remove(news);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DienMayQuyetTien/Areas/Employee/Views/ManageNews/Create.cshtml
@model DienMayQuyetTien.Models.News

@{
    ViewBag.Title = "Thêm Tin Tức";
    Layout = "~/Areas/Employee/Views/Shared/_EmpLayout.cshtml";
}




@using (Html.BeginForm("Create", "ManageNews", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()


<div class="form-control" align="center" style="  border: 1px solid;
            padding: 10px;
                box-shadow: 5px 5px #888888;border-radius: 15px; width:600px;">
    <h2>Thêm Tin Tức</h2>
    <hr />

    <div class="form-group">

        @Html.LabelFor(model => model.Title, "Tiêu Ðề", htmlAttributes: new { @class = "control-label col-md-6" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Title)
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Img, "Hình Ảnh", htmlAttributes: new { @class = "control-label col-md-6" })
        <div class="col-md-10">
            @Html.TextBox("ImageFile", null, new { type = "file", accept = "image/gif, image/jpeg, image/png", onchange = "readURL(this);", @class = "form-control" })
            @Html.ValidationMessage("ImageFile")
            <img id="HinhTT" src="" style="width:350px;height:150px;margin-top:15px" />
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Infor, "Thông Tin", htmlAttributes: new { @class = "control-label col-md-6" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Infor, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Infor)
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Check, "Trạng Thái", htmlAttributes: new { @class = "control-label col-md-6" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.Check)
                @Html.ValidationMessageFor(model => model.Check, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Thêm" class="btn btn-success" />
            &nbsp;
            @Html.ActionLink("Hủy", "Index", "ManageNews", null, new { @class = "btn btn-danger" })

        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Trở về danh sách", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
    <script>
        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $('#HinhTT')
                        .attr('src', e.target.result);
                    //.width(150)
                    //.height(200);
                };
                reader.readAsDataURL(input.files[0]);
            }
        }
    </script>
}

DienMayQuyetTien/Areas/Employee/Views/ManageNews/Delete.cshtml
@model DienMayQuyetTien.Models.News

@{
    ViewBag.Title = "Xóa Tin Tức";
    Layout = "~/Areas/Employee/Views/Shared/_EmpLayout.cshtml";
}

<h2>Xóa</h2>
<hr />
<h3>Bạn Có Chắc Chắn Muốn Xóa Mục Này ?</h3>
<div>
   
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Img)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Img)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Infor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Infor)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Check)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Check)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Cancel", "Index", "ManageNews", null, new { @class = "btn btn-danger" })
        </div>
    }
</div>

DienMayQuyetTien/Areas/Employee/Views/ManageNews/Details.cshtml
@model DienMayQuyetTien.Models.News

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Employee/Views/Shared/_EmpLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>News</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Img)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Img)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Infor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Infor)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Check)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Check)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

DienMayQuyetTien/Areas/Employee/Views/ManageNews/Edit.cshtml
@model DienMayQuyetTien.Models.News

@{
    /**/

    ViewBag.Title = "Chỉnh Sửa Tin Tức";
    Layout = "~/Areas/Employee/Views/Shared/_EmpLayout.cshtml";
}




@using (Html.BeginForm("Edit", "ManageNews", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-control" align="center" style="  border: 1px solid;
            padding: 10px;
                box-shadow: 5px 5px #888888;border-radius: 15px; width:600px;">
    <h2>Chỉnh Sửa</h2>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        @Html.LabelFor(model => model.Title, "Tiêu Ðề", htmlAttributes: new { @class = "control-label col-md-6" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Title)
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Img, "Hình Ảnh", htmlAttributes: new { @class = "control-label col-md-6" })
        <div class="col-md-10">
            @Html.TextBox("ImageFile", null, new { type = "file", accept = "image/gif, image/jpeg, image/png", onchange = "readURL(this);", @class = "form-control" })
            @Html.ValidationMessage("ImageFile")
            <img id="HinhTT" src="@Url.Action("Details", new { imageName = Model.Img })" style="width:350px;height:150px;margin-top:15px" />
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Infor, "Thông Tin", htmlAttributes: new { @class = "control-label col-md-6" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Infor, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Infor)
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Check, "Trạng Thái", htmlAttributes: new { @class = "control-label col-md-6" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.Check)
                @Html.ValidationMessageFor(model => model.Check)
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Lưu" class="btn btn-primary" />
            &nbsp;
            @Html.ActionLink("Hủy", "Index", "ManageNews", null, new { @class = "btn btn-danger" })
        </div>
    </div>
</div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $('#HinhTT')
                        .attr('src', e.target.result);
                    //.width(150)
                    //.height(200);
                };
                reader.readAsDataURL(input.files[0]);
            }
        }
    </script>
}

DienMayQuyetTien/Areas/Employee/Views/ManageNews/Index.cshtml
@model IEnumerable<DienMayQuyetTien.Models.News>

@{
    ViewBag.Title = "Quản lí Tin Túc";
    Layout = "~/Areas/Employee/Views/Shared/_EmpLayout.cshtml";
}

<h2>Quản Lí Tin Tức</h2>

<p>
    <button class="btn btn-success" onclick="location.href='@Url.Action("Create", "ManageNews")'"><i class="fa fa-plus"></i> Thêm Tin Tức</button>
</p>
<div class="card mb-3">
    <div class="card-header">
        <i class="fa fa-table"></i> Danh Sách Tin Tức
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead align="center">
                    <tr>
                        <th>Tiêu Đề</th>
                        <th>Hình Ảnh</th>
                        <th>Thông Tin</th>
                        <th>Trạng Thái</th>
                        <th>Hành Động</th>
                    </tr>
                </thead>

                <tfoot align="center">
                    <tr>
                        <th>Tiêu Đề</th>
                        <th>Hình Ảnh</th>
                        <th>Thông Tin</th>
                        <th>Trạng Thái</th>
                        <th>Hành Động</th>
                    </tr>
                </tfoot>

                <tbody align="center">
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Title)
                            </td>
                            <td>
                                <img src="/Images/@item.Img" width="120px" height="70px " />
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Infor)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Check)
                            </td>
                            <td>

                                <button class="btn btn-info" onclick="location.href='@Url.Action("Edit", "ManageNews", new { id = item.Id })'"><i class="fa fa-pencil"></i></button> |
                                <button class="btn btn-danger" onclick="location.href='@Url.Action("Delete", "ManageNews", new { id = item.Id })'"><i class="fa fa-trash"></i></button>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <div class="card-footer small text-muted"></div>

    </div>